"""Create initial tables

Revision ID: 9bd5daa3276f
Revises: 955caac64c39
Create Date: 2025-06-26 20:40:14.236278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bd5daa3276f'
down_revision: Union[str, None] = '955caac64c39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('login_history_user_id_fkey', 'login_history', type_='foreignkey')
    op.create_foreign_key(None, 'login_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_roles_user_id_fkey', 'user_roles', type_='foreignkey')
    op.drop_constraint('user_roles_role_id_fkey', 'user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.create_foreign_key('user_roles_role_id_fkey', 'user_roles', 'roles', ['role_id'], ['id'])
    op.create_foreign_key('user_roles_user_id_fkey', 'user_roles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'login_history', type_='foreignkey')
    op.create_foreign_key('login_history_user_id_fkey', 'login_history', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
